# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38c72b91c04e4507d080cbfd3278f064bf7fbe45ea96e42869678f2268ce3f300339604c0081b4d1b2d0ff62ea80b4eaab276ee4d3a71d85e72111c781a49ede

test:
  secret_key_base: 2f4abbcda194922f41894d251ff54aa2e7c8d9dca51b4b5ade9c634fbca3f8093130945f8e7f39b488de387b9309adaa06c9f9ad6e4de1b728e627e8f90ba3cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
